# Generated by Django 4.2.23 on 2025-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('md5', models.CharField(max_length=32)),
                ('mimetype', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(max_length=100)),
            ],
        ),
    ]
