# Generated by Django 4.2.23 on 2025-07-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', '正常'), ('normal', '停用')], default='normal', max_length=10, verbose_name='状态')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '字典',
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.SmallIntegerField(verbose_name='排序')),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('normal', '正常'), ('normal', '停用')], default='normal', max_length=10, verbose_name='状态')),
                ('is_default', models.CharField(choices=[('default', '是'), ('non_default', '否')], default='default', max_length=20, verbose_name='是否默认')),
                ('css_class', models.CharField(max_length=100, verbose_name='css 样式属性')),
                ('list_class', models.CharField(max_length=100, verbose_name='表格字典样式')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionary')),
            ],
            options={
                'verbose_name': '字典项',
            },
        ),
    ]
