# Generated by Django 4.2.23 on 2025-07-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': '字典', 'verbose_name_plural': '字典'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryitem',
            options={'verbose_name': '字典项', 'verbose_name_plural': '字典项'},
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='css_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='css 样式属性'),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='list_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='表格字典样式'),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='sort',
            field=models.SmallIntegerField(default=1, verbose_name='排序'),
        ),
    ]
