# Generated by Django 4.2.23 on 2025-08-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_dictionary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryitem',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dictionary.dictionary'),
        ),
    ]
