# Generated by Django 4.2.23 on 2025-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_dictionaryitem_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='配置 KEY')),
                ('value', models.TextField(verbose_name='配置值')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
