# Generated by Django 4.2.23 on 2025-08-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_sysconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconfig',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='配置值'),
        ),
    ]
