# Generated by Django 4.2.23 on 2025-08-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menu_path'),
        ('user', '0002_alter_userdetail_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名')),
                ('label', models.CharField(max_length=50, verbose_name='角色标签')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('menus', models.ManyToManyField(related_name='roles', to='menu.menu')),
            ],
        ),
    ]
