# Generated by Django 4.2.23 on 2025-08-07 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='激活图标（菜单)')),
                ('active_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='当前激活的菜单')),
                ('affix_tab', models.BooleanField(default=False, verbose_name='是否固定标签页')),
                ('affix_tab_order', models.IntegerField(default=0, verbose_name='固定标签页的顺序')),
                ('badge', models.CharField(blank=True, max_length=100, null=True, verbose_name='徽标')),
                ('badge_type', models.CharField(blank=True, choices=[('dot', '点'), ('normal', '文字')], max_length=10, null=True, verbose_name='徽标类型')),
                ('badge_variants', models.CharField(blank=True, max_length=20, null=True, verbose_name='徽标颜色')),
                ('full_path_key', models.BooleanField(default=True, verbose_name='')),
                ('hide_children_in_menu', models.BooleanField(default=False, verbose_name='')),
                ('hide_in_bread_crumb', models.BooleanField(default=False, verbose_name='')),
                ('hide_in_menu', models.BooleanField(default=False, verbose_name='')),
                ('hide_in_tab', models.BooleanField(default=False, verbose_name='')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('iframe_src', models.CharField(blank=True, max_length=200, null=True, verbose_name='iframe 地址')),
                ('ignore_access', models.BooleanField(default=False, verbose_name='')),
                ('keep_alive', models.BooleanField(default=False, verbose_name='')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='外链')),
                ('title', models.CharField(max_length=200, verbose_name='标题名称')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '菜单元属性表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='路由名称')),
                ('path', models.CharField(max_length=100, verbose_name='路由路径')),
                ('redirect', models.CharField(blank=True, max_length=100, null=True, verbose_name='重定向路径')),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.menumeta')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.menu')),
            ],
            options={
                'verbose_name': '菜单表',
            },
        ),
    ]
