# Generated by Django 4.2.23 on 2025-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumeta',
            name='full_path_key',
            field=models.BooleanField(default=True, verbose_name='是否将路由的完整路径作为tab key'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='hide_children_in_menu',
            field=models.BooleanField(default=False, verbose_name='页面的子页面是否在菜单中隐藏'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='hide_in_bread_crumb',
            field=models.BooleanField(default=False, verbose_name='页面是否在面包屑中隐藏'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='hide_in_menu',
            field=models.BooleanField(default=False, verbose_name='页面是否在菜单中隐藏'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='hide_in_tab',
            field=models.BooleanField(default=False, verbose_name='页面是否在标签页中隐藏'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='ignore_access',
            field=models.BooleanField(default=False, verbose_name='页面是否忽略权限'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='keep_alive',
            field=models.BooleanField(default=False, verbose_name='页面是否开启缓存,仅在标签页启用时有效'),
        ),
    ]
