# Generated by Django 4.2.23 on 2025-08-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_options_alter_menumeta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('folder', 'mulu'), ('page', 'yemian')], default='page', max_length=10, verbose_name='caidan leixing'),
            preserve_default=False,
        ),
    ]
