# Generated by Django 4.2.23 on 2025-08-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumeta',
            name='menu',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='menu.menu'),
        ),
    ]
