# Generated by Django 4.2.23 on 2025-08-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menumeta_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.menu', verbose_name='父路由'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('folder', '目录'), ('page', '页面'), ('button', '按钮'), ('link', '外链'), ('iframe', 'iframe')], max_length=10, verbose_name='菜单类型'),
        ),
    ]
