# Generated by Django 4.2.23 on 2025-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_status_alter_menu_parent_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组件路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('catelog', '目录'), ('page', '页面'), ('button', '按钮'), ('link', '外链'), ('iframe', 'iframe')], max_length=10, verbose_name='菜单类型'),
        ),
    ]
