# Generated by Django 4.2.23 on 2025-08-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_component_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='路由路径'),
        ),
    ]
